### ISSUE TITLE
App Does Not Work Properly

### ISSUE THREAD

**Issue by emondd4** [ikolomiyets/bluetooth-test#1]
Nothing Happed Whenever I write something on edittext field and even hit on button!

**Comment by ikolomiyets** [comment]
There are number of reasons why this could happen from hardware incompatibility to changes at the OS level.
Bear in mind that it was written as an example couple of years ago and things might move on since.

Moreover, this example is just a guideline how to proceed when you want to enable bluetooth communication between the devices in your project. It never meant to be a complete product which supposed to work on any device.

**Comment by emondd4** [comment]
I Understand its not a complete product and its a guideline. and thats why i was here. but after downloading it I found its not working properly, not even in api 21. 

anyways, thanks for your response. Have a good day!
